"""add quantity to booking

Revision ID: 21f9b6bd1305
Revises: 45b83b2790be
Create Date: 2026-06-21 15:21:11.037526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21f9b6bd1305'
down_revision = '45b83b2790be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
